name: Deploy to remote server using Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote docker
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          ssh_public_key: ${{ secrets.PUBLIC_SSH_KEY }}
          deployment_mode: docker-compose
          stack_file_name: docker-compose.yml
          args: up -d
